### ISSUE TITLE
[Bug]: Only the first Netmaker server register

### ISSUE THREAD

**Issue by MinDBreaK** [gravitl/netmaker#1261]
### Contact Details

antoine@aiherd.io

### What happened?

I'm currently setting up a HA cluster with netmaker. 
While I could successfully set every component in HA, I hit a problem with netmaker, where only the first node would register.  All the nodes have the same configuration, with separate `NODE_ID`, but same `SERVER_HOST` (because it is behind a LoadBalancer). However, only one node appear on the UI, and the others do not seem to connect and the wireguard tunnel is not up.

Here is the configuration of the netmaker container, If you need more containers, just ask and I'll provide them.

For information, the mq container is a rabbitmq + rabbitmq_mqtt extension for HA needs. And the Wireguard can successfully join with the netclient command as long as the client reach the one running

In the following configuration, the `netmaker_public_ip` is the public IP of the load balancer. 
Current architecture is the following : 

`Client ----> AWS Network Load Balancer -----> (Netmaker Server + rqlite + amqp + netmaker-ui) * 3`

Configuration : 
 
```yaml
services:
  netmaker:
    container_name: netmaker
    image: gravitl/netmaker:v0.14.3
    volumes:
      - dnsconfig:/root/config/dnsconfig
      - sqldata:/root/data
      - $PWD/docker/certs:/etc/netmaker/
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
    restart: always
    environment:
      VERBOSITY: "3"
      DISABLE_REMOTE_IP_CHECK: "true"
      SERVER_NAME: "broker.netmaker.domain.tld"
      SERVER_HOST: "{{ netmaker_public_ip }}"
      SERVER_API_CONN_STRING: "api.netmaker.domain.tld:443"
      SERVER_HTTP_HOST: "api.netmaker.domain.tld"
      NODE_ID: "netmaker_<id>"
      API_PORT: "8081"
      MQ_HOST: "amqp"
      DATABASE: "rqlite"
      SQL_CONN: "http://user:pass@rqlite:4001/"
      CLIENT_MODE: "on"
      MASTER_KEY: "REDACTED"
      CORS_ALLOWED_ORIGIN: "*"
      DISPLAY_KEYS: "on"
      HOST_NETWORK: "off"
      MANAGE_IPTABLES: "on"
      DNS_MODE: "off"
      COREDNS_ADDR: "{{ netmaker_host }}"
      PORT_FORWARD_SERVICES: ""
      AUTH_PROVIDER: "google"
      CLIENT_ID: "{{ oauth_client_id }}"
      CLIENT_SECRET: "{{ oauth_client_secret }}"
      FRONTEND_URL: "https://dashboard.netmaker.domain.tld"
    ports:
      - "51821-51830:51821-51830/udp"
# [...]
```

### Version

v0.14.3

### What OS are you using?

Linux

### Relevant log output

```shell
#### 
## NODE 1
####
netmaker  | [netmaker] 2022-06-28 14:09:15 connecting to rqlite
netmaker  | [netmaker] 2022-06-28 14:09:22 database successfully connected
netmaker  | [netmaker] 2022-06-28 14:09:24 external OAuth detected, proceeding with https redirect: (https://api.netmaker.example.tld)
netmaker  | [netmaker] 2022-06-28 14:09:24 OAuth provider, google, initialized
netmaker  | [netmaker] 2022-06-28 14:09:27 setting iptables forward policy
netmaker  | [netmaker] 2022-06-28 14:09:27 checking keys and certificates
netmaker  | [netmaker] 2022-06-28 14:09:28 publishing node update to test-client
netmaker  | [netmaker] 2022-06-28 14:09:30 REST Server successfully started on port  8081  (REST)
netmaker  | [netmaker] 2022-06-28 14:09:30 connecting to mq broker at amqp:1883
netmaker  | [netmaker] 2022-06-28 14:11:00 error getting node  592f3c03-fa6c-4edd-b646-82b0dc532d3b no result found
netmaker  | [netmaker] 2022-06-28 14:14:41 setting iptables forward policy
netmaker  | [netmaker] 2022-06-28 14:14:45 sending scheduled peer update (5 min)

####
## NODE 2
####
netmaker  | [netmaker] 2022-06-28 14:32:50 connecting to rqlite
netmaker  | [netmaker] 2022-06-28 14:32:55 database successfully connected
netmaker  | [netmaker] 2022-06-28 14:32:56 external OAuth detected, proceeding with https redirect: (https://api.netmaker.example.tld)
netmaker  | [netmaker] 2022-06-28 14:32:56 OAuth provider, google, initialized
netmaker  | [netmaker] 2022-06-28 14:32:58 setting iptables forward policy
netmaker  | [netmaker] 2022-06-28 14:32:58 checking keys and certificates
netmaker  | [netmaker] 2022-06-28 14:32:59 REST Server successfully started on port  8081  (REST)
netmaker  | [netmaker] 2022-06-28 14:32:59 connecting to mq broker at amqp:1883
netmaker  | [netmaker] 2022-06-28 14:38:08 setting iptables forward policy
netmaker  | [netmaker] 2022-06-28 14:38:11 sending scheduled peer update (5 min)

####
## NODE 3
####

netmaker  | [netmaker] 2022-06-28 14:09:16 connecting to rqlite
netmaker  | [netmaker] 2022-06-28 14:09:23 database successfully connected
netmaker  | [netmaker] 2022-06-28 14:09:25 external OAuth detected, proceeding with https redirect: (https://api.netmaker.example.tld)
netmaker  | [netmaker] 2022-06-28 14:09:25 OAuth provider, google, initialized
netmaker  | [netmaker] 2022-06-28 14:09:28 setting iptables forward policy
netmaker  | [netmaker] 2022-06-28 14:09:28 checking keys and certificates
netmaker  | [netmaker] 2022-06-28 14:09:28 publishing node update to test-peer
netmaker  | [netmaker] 2022-06-28 14:09:31 REST Server successfully started on port  8081  (REST)
netmaker  | [netmaker] 2022-06-28 14:09:31 connecting to mq broker at amqp:1883
netmaker  | [netmaker] 2022-06-28 14:10:59 no zombies found
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
This is a known issue in the latest version(s), we are working to resolve this issue and will have a fix in the next release (v0.14.5)

**Comment by MinDBreaK** [comment]
Thank you !

**Comment by afeiszli** [comment]
HA is fixed in v0.14.5

**Comment by MinDBreaK** [comment]
Hello, 
It does not appear to be completely fixed, I did have 3 nodes that register, however, two took the same id, despite beeing set two differents one. 

I currently have `netmaker-1`, `netmaker-2` and `netmaker-2`. 

Also it still does not allow setting upfront a different endpoint while the servers are behind a load balancer.
